version: '3'
services:
  db:
    image: "mysql/mysql-server:latest"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    expose:
     - "3306"
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: 'cas'
     MYSQL_USER: 'user'
     MYSQL_PASSWORD: 'pass'
    volumes:
     - "/opt/mysql/data:/var/lib/mysql"
  mq:
    image: "rabbitmq:latest"
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
