server:
  port: 7070

---
spring:
  profiles: docker-local
  datasource:
#     schema: classpath:/sql/schema.sql
#     data: classpath:/sql/data.sql
     url: jdbc:mysql://localhost:3306/cas?autoReconnect=true&useSSL=false
     username: user
     password: pass
     driverClassName: com.mysql.jdbc.Driver
#       tomcat:
#         max-active: 5
     dbcp2:
       initial-size: 2
       max-total: 10
       pool-prepared-statements: true
#         url: jdbc:mysql://localhost:3306/db
#         driver-class-name: com.mysql.jdbc.Driver
#         username: user
#         password: pass

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
#    database: 1
  cloud:
    loadbalancer:
      retry:
        enabled: true

#    database: 0
#    port: 6379
#    cluster:
#      nodes: 127.0.0.1:6379,...


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    users-test:
      path: /test/**
      serviceId: api-test
      stripPrefix: false
    oauth:
      path: /uua/**
      serviceId: oauth2
#      sensitive-headers: Authorization,Cookie,Set-Cookie
#      sensitiveHeaders: Access-Control-Allow-Origin
      sensitiveHeaders:
#      ignoredHeaders: Access-Control-Allow-Origin
#      sensitiveHeader: Access-Control-Allow-Origin, Access-Control-Allow-Methods
      stripPrefix: false
    advertising:
      path: /advertising/**
#      url: http://localhost:6767/
      serviceId: cas-ads
      stripPrefix: false
    schools:
      path: /schools/**
#      url: http://localhost:6767/
      serviceId: cas-schools
      stripPrefix: false
    dicts: # dicts and sys-dicts
      path: /dicts/**
#      url: http://localhost:6767/
      serviceId: cas-dicts
      stripPrefix: false
    users: # user role group
      path: /users/**
#      url: http://localhost:6767/
      serviceId: cas-users
      stripPrefix: false
    roles:
      path: /roles/**
#      url: http://localhost:6767/
      serviceId: cas-roles
      stripPrefix: false
    classes: # class and arrangement
      path: /classes/**
      serviceId: cas-classes
      stripPrefix: false
    classrooms: # classroom
      path: /classrooms/**
      serviceId: cas-classrooms
      stripPrefix: false
    courses:
      path: /courses/**
      serviceId: cas-courses
      stripPrefix: false
    todos:
      path: /todos/**
      serviceId: cas-todos
      stripPrefix: false
    announcements:
      path: /announcements/**
      serviceId: cas-announcements
      stripPrefix: false
    payments:
      path: /payments/**
      serviceId: cas-payments
      stripPrefix: false
    logs: # audit log, operation log, payment log etc.
      path: /payments/**
      serviceId: cas-payments
      stripPrefix: false
    assets:
      path: /assets/**
#      url: http://localhost:6767/
      serviceId: cas-assets
      stripPrefix: false
    calendar:
      path: /calendar/**
      serviceId: cas-calendar
      stripPrefix: false
    preselect:
      path: /preselect/**
      serviceId: cas-preselect
      stripPrefix: false
    contracts:
      path: /contracts/**
      serviceId: cas-contracts
      stripPrefix: false
    expenses:
      path: /expenses/**
      serviceId: cas-expenses
      stripPrefix: false
    tasks:
      path: /tasks/**
      serviceId: cas-tasks
      stripPrefix: false
    registrations:
      path: /registrations/**
      serviceId: cas-registrations
      stripPrefix: false
    statistics:
      path: /statistics/**
      serviceId: cas-statistics
      stripPrefix: false
    preselects:
      path: /preselects/**
      serviceId: cas-preselects
      stripPrefix: false
    appeals:
      path: /appeals/**
      serviceId: cas-appeals
      stripPrefix: false
    teachers:
      path: /teachers/**
      serviceId: cas-teachers
      stripPrefix: false
    students:
      path: /students/**
      serviceId: cas-students
      stripPrefix: false
  prefix: /api
  whitelist: /health_check,/uua/v*/login,/uua/v*/baseinfo,/uua/v*/oauth/token,/uua/v*/oauth/authorize,/uua/v*/oauth/confirm_access,/advertising/v*/publicads
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 10000
  retryable: true
#  ribbon-isolation-strategy: thread

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
  threadpool.default.coreSize: 20

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9191/uua/v1/oauth/token
      userAuthorizationUri: http://localhost:9191/uua/v1/oauth/authorize
      clientId: base_course_app
      clientSecret: secret
      client-authentication-scheme: header
    resource:
      userInfoUri: http://localhost:9191/uua/v1/user
#      preferTokenInfo: false
#   depracated in Springboot 2
#      filter-order: 3
#  sessions: ALWAYS
#  headers:
#    frame: true

---
spring:
  profiles: docker
  datasource:
#     schema: classpath:/sql/schema.sql
#     data: classpath:/sql/data.sql
     url: jdbc:mysql://10.16.156.36:3306/cas?autoReconnect=true&useSSL=false
     username: user
     password: pass
     driverClassName: com.mysql.jdbc.Driver
#       tomcat:
#         max-active: 5
     dbcp2:
       initial-size: 2
       max-total: 10
       pool-prepared-statements: true
#         url: jdbc:mysql://localhost:3306/db
#         driver-class-name: com.mysql.jdbc.Driver
#         username: user
#         password: pass

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 10.16.156.36
    port: 6379
    database: 0
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://10.16.156.36:8761/eureka/
  instance:
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds:
#    ip-address:


zuul:
  routes:
    users-test:
      path: /test/**
      serviceId: api-test
      stripPrefix: false
    oauth:
      path: /uua/**
      serviceId: oauth2
#      sensitive-headers: Authorization,Cookie,Set-Cookie
      sensitiveHeaders:
      stripPrefix: false
    advertising:
      path: /advertising/**
#      url: http://localhost:6767/
      serviceId: cas-ads
      stripPrefix: false
    schools: # schools and campus
      path: /schools/**
#      url: http://localhost:6767/
      serviceId: cas-schools
      stripPrefix: false
    dicts: # dicts and sys-dicts
      path: /dicts/**
#      url: http://localhost:6767/
      serviceId: cas-dicts
      stripPrefix: false
    users: # user role group
      path: /users/**
#      url: http://localhost:6767/
      serviceId: cas-users
      stripPrefix: false
    roles:
      path: /roles/**
#      url: http://localhost:6767/
      serviceId: cas-roles
      stripPrefix: false
    classes: # class and arrangement
      path: /classes/**
      serviceId: cas-classes
      stripPrefix: false
    classrooms: # classroom
      path: /classrooms/**
      serviceId: cas-classrooms
      stripPrefix: false
    courses:
      path: /courses/**
      serviceId: cas-courses
      stripPrefix: false
    todos:
      path: /todos/**
      serviceId: cas-todos
      stripPrefix: false
    announcements:
      path: /announcements/**
      serviceId: cas-announcements
      stripPrefix: false
    payments:
      path: /payments/**
      serviceId: cas-payments
      stripPrefix: false
    logs: # audit log, operation log, payment log etc.
      path: /payments/**
      serviceId: cas-payments
      stripPrefix: false
    assets:
      path: /assets/**
#      url: http://localhost:6767/
      serviceId: cas-assets
      stripPrefix: false
    calendar:
      path: /calendar/**
      serviceId: cas-calendar
      stripPrefix: false
    preselect:
      path: /preselect/**
      serviceId: cas-preselect
      stripPrefix: false
    contracts:
      path: /contracts/**
      serviceId: cas-contracts
      stripPrefix: false
    expenses:
      path: /expenses/**
      serviceId: cas-expenses
      stripPrefix: false
    tasks:
      path: /tasks/**
      serviceId: cas-tasks
      stripPrefix: false
    registrations:
      path: /registrations/**
      serviceId: cas-registrations
      stripPrefix: false
    statistics:
      path: /statistics/**
      serviceId: cas-statistics
      stripPrefix: false
    preselects:
      path: /preselects/**
      serviceId: cas-preselects
      stripPrefix: false
    appeals:
      path: /appeals/**
      serviceId: cas-appeals
      stripPrefix: false
    teachers:
      path: /teachers/**
      serviceId: cas-teachers
      stripPrefix: false
    students:
      path: /students/**
      serviceId: cas-students
      stripPrefix: false
  prefix: /api
  whitelist: /health_check,/uua/v*/login,/uua/v*/baseinfo,/uua/v*/oauth/token,/uua/v*/oauth/authorize,/uua/v*/oauth/confirm_access,/advertising/v*/publicads
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 10000
  retryable: true
#  ribbon-isolation-strategy: thread

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
  threadpool.default.coreSize: 20

security:
  oauth2:
    client:
      accessTokenUri: http://${oauthip:10.16.156.36}:${oauthport:9191}/uua/v1/oauth/token
      userAuthorizationUri: http://${oauthip:10.16.156.36}:${oauthport:9191}/uua/v1/oauth/authorize
      clientId: base_course_app
      clientSecret: secret
      client-authentication-scheme: header
    resource:
      userInfoUri: http://${oauthip:10.16.156.36}:${oauthport:9191}/uua/v1/user
#      preferTokenInfo: false
#      filter-order: 3

#  sessions: ALWAYS