info:
  component: api-test

server:
  port: ${smng.application.port:9098}
  contextPath: /test


eureka:
  client:
    serviceUrl:
      defaultZone: ${smng.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

spring:
  rabbitmq:
#    addresses: ${cmng.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}
    host: localhost
    port: 5672
#    username: jpkszgmu
#    password: test

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9191/uua/oauth/token
      userAuthorizationUri: http://localhost:9191/uua/oauth/authorize
      clientId: base_course_app
      clientSecret: secret
      client-authentication-scheme: header
    resource:
      userInfoUri: http://localhost:9191/uua/user
      filter-order: 3

logging:
  level: debug
  path: ${HOME}/project/logs/api_test


---
spring:
  profiles: cloud
eureka:
  instance:
    instance-id: api-test-instance
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80

