
server:
  port: 8761

eureka:
  instance:
    hostname: s1
#    lease-expiration-duration-in-seconds: 90
#    lease-renewal-interval-in-seconds: 30
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://192.168.0.10:8762/eureka/
#    register-with-eureka: true
  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    renewal-percent-threshold: 0.85
#    Set to default 0.85 when there is a cluster
    renewal-percent-threshold: 0.49
#    renewal-threshold-update-interval-ms: 0
