
server:
  port: 8761

eureka:
  instance:
    hostname: s1
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://192.168.0.10:8762/eureka/
#    register-with-eureka: true
  server:
    waitTimeInMsWhenSyncEmpty: 0